### ISSUE TITLE
Implement parametric bootstrap for TMB models

### ISSUE THREAD

**Issue by joethorley** [bcgov/ssdtools#200]
> I think a "conservative" result will be to take the largest of the <values, and the smallest of the >values from our dataset and apply these to the bootstrap data. This may "overcensor" the data, but I think it is best we can do. For smallist datasets (i.e. <= 10 values), I think that the general noise and uncertainty about the fitted distributions will overwhelm any additional problems caused by too conservative censoring.

For weights simply reassign in order of size?

Note previously fitdistrplus only did non-parametric for censored data.

**Comment by cschwarz-stat-sfu-ca** [comment]
Hmm... hadn't thought about weights...Again, I don't think there is enough
information in the weight values to know what to do. Presumably the weights
are in indication of the reliability of the result (e.g. inversely
proportional the uncertainty in each endpoint) which can't be captured by
the bootstrap in its current form; or weights want to give more emphasis to
fish species rather than plant species- again unable to capture this.  All
of these cases are good arguments for going full Bayesian...

My suggestion is that if there unequal weights, give a LARGE warning that
the weights will be ignored in the bootstrapping, and you need to contact
us and set up a contract so we can figure out what you really want to do
with weights.

Carl

**Comment by joethorley** [comment]
That sounds like plan.

**Comment by joethorley** [comment]
Doesn't do bootstrapping for unequal weights or inconsistently censored data.

```
  if(ci && identical(censoring, c(NA_real_, NA_real_))) {
    wrn("CIs cannot be calculated for inconsistently censored data.")
    ci <- FALSE
  }
  
  if(ci && unequal) {
    wrn("CIs cannot be calculated for unequally weighted data.")
    ci <- FALSE
  }
  ```
