### ISSUE TITLE
vignette on small sample size bias

### ISSUE THREAD

**Issue by joethorley** [bcgov/ssdtools#47]
log-normal and gamma

**Comment by EmilieDouss** [comment]
Hi Joe,

Could you please unsubscribe me of GitHub for ssdtools?

I have a new position since april, absolutely unrelated with ssdtools. Marianne Metivier took my job.  Ally and Angeline know that and I’m sure they know Marianne now.

Have a good day !!!

Émilie

Émilie Doussantousse, bio. Ph. D.
Coordonnatrice – Volet légal et réglementaire
Bureau de la mise en œuvre de la modernisation
Ministère de l’Environnement
et de la Lutte contre les changements climatiques
1175, boul. Lebourgneuf, bureau 100
Québec (Québec) G2K 0B7

• 418 644-8844, p. 281
• fax 418 646-1214
• Emilie.doussantousse@environnement.gouv.qc.ca<mailto:Emilie.doussantousse@environnement.gouv.qc.ca>




De : Joe Thorley [mailto:notifications@github.com]
Envoyé : 25 novembre 2019 15:24
À : bcgov/ssdtools <ssdtools@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : [bcgov/ssdtools] vignette on small sample size bias (#47)


log-normal and gamma

**Comment by joethorley** [comment]
Hi Émilie

You need to unwatch the repository.

<img width="1075" alt="Screen Shot 2019-11-25 at 13 56 01" src="https://user-images.githubusercontent.com/613671/69581571-97362400-0f8b-11ea-8be5-12d67a943f4e.png">

**Comment by cschwarz-stat-sfu-ca** [comment]
VIgnette completed and sent to JT for integration into package. Car.
