### ISSUE TITLE
check distributions

### ISSUE THREAD

**Issue by joethorley** [bcgov/ssdtools#71]
confirm AICc same as report

**Comment by joethorley** [comment]
and that can generate HC5s

**Comment by joethorley** [comment]
done

**Comment by joethorley** [comment]
@cschwarz-stat-sfu-ca - Can you check each of the distributions including their parameter names and default values.

In particular I'm concerned about dllogis which currently has 

```dlogis(log(x), location = exp(lscale), scale = exp(lshape)) / x```

for the density. The division by x seems wrong to me.

Links to all the distributional code is below.

https://github.com/bcgov/ssdtools/blob/master/R/burrIII2.R
https://github.com/bcgov/ssdtools/blob/master/R/burrIII3.R
https://github.com/bcgov/ssdtools/blob/master/R/gamma.R
https://github.com/bcgov/ssdtools/blob/master/R/gompertz.R
https://github.com/bcgov/ssdtools/blob/master/R/lgumbel.R
https://github.com/bcgov/ssdtools/blob/master/R/llogis.R
https://github.com/bcgov/ssdtools/blob/master/R/pareto.R
https://github.com/bcgov/ssdtools/blob/master/R/weibull.R

You can see the distributions plotted at https://bcgov.github.io/ssdtools/articles/distributions.html

**Comment by cschwarz-stat-sfu-ca** [comment]
I looked over the distributions and have the following commentsl
- gumbel distribution... why not pass the log= argument to the vgam function the body? See the llogis() distribution for an example


------- Comments about transformations ....
Let F_x(x) = cumulative distribution function of x, i.e integrate(-inf, x) f(x) dx. Say the logistic distribution on the log-scale.

get y = g(x) be the transformation of x, e.g. y=exp(x), i.e. on the concentration scale.

The cumulative distribution of Y is then 
   F_y (y) = integrate(-inf, y) f(y) dy which is the log-logistic distribtuion

We do a variable transformation
   F_y(y) = F_x( ginv(y)) 
where ginv = inverse function of y and the density function is the first derivative. So here ginv(y) = log(y).

We now find the density function 
   f_y(y) = F'_y(y) = F'_x(ginv(x)) ginv'(x) dx = f_x( ginv(x)) ginv'(x)
where F" is the first derivative, and ginv' is the derivative of the inverse function.

The latter term comes from   derivative of ( h(k(x)) =h'(k(x)) k'(x) dx

We now evaluate
  density of log-logistic - density logistic(evaluated at log(x)) 1/x  since derivative of log(x) is 1/x.

See http://math.bme.hu/~nandori/Virtual_lab/stat/dist/Transformations.pdf for the gory details.

--------------------------

Distribution plot... these should likely be plotted with the the distribution having the same mean and variance (on the log scale) so that the difference among the densities in the tails can be seen.

I'll write you a function to find the parameter values to match the mean and variance on the log-scale for a given distribution function using BFI.

Carl.
